server/views.py
"""
This module contains the routes for serving the HTML files.
"""
from datetime import datetime
from functools import wraps
from flask import Blueprint
from flask import render_template, request, redirect, url_for, flash, session
from werkzeug.security import generate_password_hash, check_password_hash
from database import ProjectManagersHandler, VehiclesHandler, UsersHandler
from database import RegistrationStates

# This route is for serving the HTML files.
PageRoutes = Blueprint("PageRoutes", __name__)


def login_required(route_function):
    """It is a decorator that checks if the user is logged in."""
    @wraps(route_function)
    def decorated_function(*args, **kwargs):
        if not session.get("logged_in"):
            flash({"text": "Please log in to access this page.", "msg_type": "warning"})
            return redirect(url_for("PageRoutes.login"))
        return route_function(*args, **kwargs)

    return decorated_function


@PageRoutes.route("/", methods=["GET"])
def index():
    """It provides the index page."""
    return render_template("index.html", logged_in=session.get("logged_in"))


@PageRoutes.route("/about-us", methods=["GET"])
def about_us():
    """It provides the about us page."""
    # Retrieve the project managers from the database.
    project_managers = ProjectManagersHandler().get_all_information()
    return render_template("about_us.html",
                           members=project_managers,
                           logged_in=session.get("logged_in"))


@PageRoutes.route("/project_details", methods=["GET"])
def project_details():
    """It provides the project details page."""
    return render_template("project_details.html", logged_in=session.get("logged_in"))


@PageRoutes.route("/login", methods=["GET", "POST"])
def login():
    """It provides the login page."""
    if request.method == "POST":
        email = request.form["email"]
        password = request.form["password"]

        user = UsersHandler()
        user_exist = user.check_email(email)
        if not user_exist or not check_password_hash(
            user.get_password_hash(email), password
        ):
            flash({"text": "Please check your login details and try again.", "msg_type": "warning"})
            return redirect(url_for("PageRoutes.login"))
        else:
            session["logged_in"] = True
            return redirect(url_for("PageRoutes.dashboard"))

    # If request made with GET, render the login page.
    return render_template("login.html")


@PageRoutes.route("/signup", methods=["GET", "POST"])
def signup():
    """It provides the signup page."""
    if request.method == "POST":
        name_surname = request.form["name_surname"]
        company = request.form["company"]
        email = request.form["email"]
        password = request.form["password"]
        password = generate_password_hash(password, method="sha256")
        users_handler = UsersHandler()

        result = users_handler.register_user(
            {
                "name_surname": name_surname,
                "company": company,
                "email": email,
                "password": password,
            }
        )

        if result == RegistrationStates.NOT_REGISTERED:
            flash({"text": "Something went wrong. Please try again.", "msg_type": "warning"})
            return redirect(url_for("PageRoutes.signup"))
        elif result == RegistrationStates.ALREADY_REGISTERED:
            flash({"text": "Email address already exists", "msg_type": "warning"})
            return redirect(url_for("PageRoutes.signup"))
        elif result == RegistrationStates.SUCCESS:
            flash({"text": "User registered successfully!", "msg_type": "primary"})
            return redirect(url_for("PageRoutes.login"))
        else:
            flash({"text": "Something went wrong. Please try again.", "msg_type": "warning"})
            return redirect(url_for("PageRoutes.signup"))
    else:
        return render_template("signup.html")


@PageRoutes.route("/dashboard", methods=["GET"])
@login_required
def dashboard():
    """It provides the dashboard page."""
    # Retrieve the vehicles from the database
    if not session.get("logged_in"):
        return redirect(url_for("PageRoutes.login"))
    vehicles = VehiclesHandler().get_all_information()
    return render_template("dashboard.html",
                           datatable=vehicles,
                           customer_id="01",
                           company_name="IETT",
                           page_name="Dashboard",
                           summary_information={"total": 86, "planned": 15, "required": 19},
                           suggestions=[
                               "Consider changing M4.56's route with M4.57's route.",
                                "34KLM56 is not in the route. Please check it."
                            ],
                            user_name="John Doe"
                           )


@PageRoutes.route("/details", methods=["GET"])
@login_required
def details():
    """It provides the vehicle details page."""
    query_arguments = request.args.to_dict()
    if not query_arguments:
        flash({"text": "Please select a vehicle to view details.", "msg_type": "warning"})
        return redirect(url_for("PageRoutes.dashboard"))

    vehicle_id = query_arguments["vid"]
    customer_id = query_arguments["cid"]

    selected_vehicle = None
    for vehicle in VehiclesHandler().get_all_information():
        if vehicle["vid"].lower() == vehicle_id.lower():
            selected_vehicle = vehicle
            break

    if not selected_vehicle:
        flash({"text": "Please select a vehicle to view details.", "msg_type": "warning"})
        return redirect(url_for("PageRoutes.dashboard"))

    return render_template("details.html",
        user_name="John Doe",
        company_name="IETT",
        page_name="Vehicle Details",
        image_location="metro_image.png",
        vehicle_details={
            "vehicle_id": vehicle_id,
            "customer_id": customer_id,
            "plate": selected_vehicle.get("plate"),
            "route": selected_vehicle.get("route"),
            "last_date": selected_vehicle.get("last_date"),
            "class": selected_vehicle.get("class"),
            "status": "Active",
            "last_location": f"Longitude: {selected_vehicle.get('gps_longitude')}, "
                             f"Latitude: {selected_vehicle.get('gps_latitude')}",
            "battery": selected_vehicle.get("battery"),
        },
        driver_details={
            "profile_photo": "bus_driver.jpg",
            "name": "John Doe",
            "phone": "+90 532 123 45 67",
        },
        prediction_details={
            "failure_date": "05/11/2023",
            "failure_reason": "Piston corrosion on cyclinder 3",
        },
        back_link="/dashboard",
    )


@PageRoutes.route("/profile", methods=["GET"])
@login_required
def profile():
    """It provides the profile page."""
    return render_template("profile.html",
                           company_name="IETT",
                           page_name="Profile")


@PageRoutes.route("/logout")
@login_required
def logout():
    """It provides the logout page."""
    session.clear()
    return redirect(url_for("PageRoutes.login"))


@PageRoutes.route("/devices/register", methods=["GET", "POST"])
@login_required
def device_register():
    """It provides the device register page."""
    if request.method == "POST":
        # If not logged in, redirect to login page.
        if not session.get("logged_in"):
            return redirect(url_for("login"))

        device_id = request.form["device_id"]
        vehicle_type = request.form["vehicle_type"]
        plate = request.form["plate"]
        route = request.form["route"]
        last_date = request.form["last_date"]
        last_date = datetime.strptime(last_date, "%Y-%m-%d")

        vehicles_handler = VehiclesHandler()
        result = vehicles_handler.register_device(
            {
                "device_id": device_id,
                "class": vehicle_type,
                "plate": plate,
                "route": route,
                "last_date": last_date,
            }
        )

        if result == RegistrationStates.NOT_REGISTERED:
            flash({"text": "Something went wrong. Please try again.", "msg_type": "warning"})
            return redirect(url_for("PageRoutes.device_register"))
        elif result == RegistrationStates.ALREADY_REGISTERED:
            flash({"text": "Device already registered.", "msg_type": "warning"})
            return redirect(url_for("PageRoutes.device_register"))
        elif result == RegistrationStates.SUCCESS:
            flash({"text": "Device registered successfully!", "msg_type": "primary"})
            return redirect(url_for("PageRoutes.dashboard"))

    # Render the register page if request made with GET.
    return render_template("register_device.html",
                           company_name="IETT",
                           page_name="Register New Device",
                           user_name="John Doe",
                           vehicle_types=[
                            {"id": 0, "name": "Bus"},
                            {"id": 1, "name": "Tram"},
                            {"id": 2, "name": "Metrobus"},
                            {"id": 3, "name": "Metro"},
                            {"id": 4, "name": "Ferry"},
                            {"id": 5, "name": "Marmaray"},
                            {"id": 7, "name": "Funicular"},
                           ])

server/templates/about_us.html
{% extends 'partials/base.html' %}

{% block content %}
<div class="columns">
    {% for member in members %}
    <div class="column">
        <div class="card">
            <div class="card-image">
                <figure class="image is-4by3">
                    <img src="{{member.profile_img_location}}">
                </figure>
            </div>
            <div class="card-content">
                <div class="media">
                    <div class="media-content">
                        <p class="title is-4">{{member.name_surname}}</p>
                        <a href="https://linkedin.com/in/{{member.social_link}}">
                            <p class="subtitle is-6">@{{member.social_link}}</p>
                        </a>
                    </div>
                </div>

                <div class="content">
                    {{member.description}}
                    <br>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

server/templates/dashboard.html
{% extends 'dashboard_partials/base.html' %}

{% block content %}

<script>
  function sortTable() {
    // Declare variables
    var input, filter, table, tr, td, i, txtValue;
    input = document.getElementById("myInput");
    filter = input.value.toUpperCase();
    table = document.getElementById("vehicleDetailsTable");
    tr = table.getElementsByTagName("tr");

    // Loop through all table rows, and hide those who don't match the search query
    for (i = 0; i < tr.length; i++) {
      td = tr[i].getElementsByTagName("td")[1];
      if (td) {
        txtValue = td.textContent || td.innerText;
        if (txtValue.toUpperCase().indexOf(filter) > -1) {
          tr[i].style.display = "";
        } else {
          tr[i].style.display = "none";
        }
      }
    }
  }

  document.addEventListener('DOMContentLoaded', function () {
    const table = document.getElementById('vehicleDetailsTable');
    const tbody = table.querySelector('tbody');
    const sortDate = document.getElementById('sortDate');
    let ascending = true;

    function sortTable() {
      const rows = Array.from(tbody.querySelectorAll('tr'));

      rows.sort((a, b) => {
        const dateA = new Date(a.querySelector('td:nth-child(5)').textContent);
        const dateB = new Date(b.querySelector('td:nth-child(5)').textContent);

        if (ascending) {
          return dateA - dateB;
        } else {
          return dateB - dateA;
        }
      });

      tbody.innerHTML = '';
      for (const row of rows) {
        tbody.appendChild(row);
      }

      ascending = !ascending;
    }

    sortDate.addEventListener('click', sortTable);
  });

</script>

<div class="columns">
  <div class="column is-9">
    <div class="columns">
      <div class="column is-one-third">
        <div class="card tile is-child">
          <div class="card-content">
            <div class="level is-mobile">
              <div class="level-item">
                <div class="is-widget-label">
                  <h3 class="subtitle is-spaced">
                    Total
                  </h3>
                  <h1 class="title">
                    {{summary_information['total']}}
                  </h1>
                </div>
              </div>
              <div class="level-item has-widget-icon">
                <div class="is-widget-icon"><span class="icon has-text-primary is-large"><i
                      class="mdi mdi-train-car mdi-48px"></i></span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="column is-one-third">
        <div class="card tile is-child">
          <div class="card-content">
            <div class="level is-mobile">
              <div class="level-item">
                <div class="is-widget-label">
                  <h3 class="subtitle is-spaced">
                    Required
                  </h3>
                  <h1 class="title">
                    {{summary_information['required']}}
                  </h1>
                </div>
              </div>
              <div class="level-item has-widget-icon">
                <div class="is-widget-icon"><span class="icon has-text-warning is-large"><i
                      class="mdi mdi-information-box mdi-48px"></i></span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="column is-one-third">
        <div class="card tile is-child">
          <div class="card-content">
            <div class="level is-mobile">
              <div class="level-item">
                <div class="is-widget-label">
                  <h3 class="subtitle is-spaced">
                    Planned 
                  </h3>
                  <h1 class="title">
                    {{summary_information['planned']}}
                  </h1>
                </div>
              </div>
              <div class="level-item has-widget-icon">
                <div class="is-widget-icon"><span class="icon has-text-danger is-large"><i
                      class="mdi mdi-train-car-flatbed-car mdi-48px"></i></span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="card has-table">

      <header class="card-header has-background-white-ter">
        <p class="card-header-title">
          <span class="icon"><i class="mdi mdi-account-multiple"></i></span>
          Vehicles
        </p>
      </header>

      <div class="card-content">
        <div class="field is-grouped">
          <p class="control is-expanded">
            <input class="input" type="text" id="myInput" onkeyup="sortTable()"
              placeholder="Find a vehicle from licence plate...">
          </p>
          <p class="control">
            <a class="button is-dark is-outlined" href="{{ url_for('PageRoutes.device_register') }}">
              Register New Vehicle
            </a>
          </p>
        </div>

        <table class="table is-striped is-hoverable is-fullwidth" id="vehicleDetailsTable">
          <thead>
            <tr>
              <th style="text-align: center;">VID</th>
              <th style="text-align: center;">Type</th>
              <th style="text-align: center;">Plate</th>
              <th style="text-align: center;">Route</th>
              <th style="text-align: center;">
                <a id="sortDate" class="sortable-header">
                  <span class="icon-text ">
                    <span>Predicted Date</span>
                    <span class="icon">
                      <i class="mdi mdi-sort-calendar-descending mdi mdi-24px"></i>
                    </span>
                  </span>
                </a>
              </th>
              <th style="text-align: center;"></th>
            </tr>
          </thead>
          <tbody>
            {% for vehicle in datatable %}
            <tr>
              <th>{{vehicle.vid}}</th>
              <td>{{vehicle.class}}</td>
              <td>{{vehicle.plate}}</td>
              <td>{{vehicle.route}}</td>
              <td>{{vehicle.pmdate}}</td>
              <td class="is-actions-cell">
                <div class="buttons is-right">
                  <button class="button is-small is-light" type="button">
                    <a class="sortable-header" href="{{url_for('PageRoutes.details')}}?vid={{vehicle.vid}}&cid={{customer_id}}">
                      <span class="icon"><i class="mdi mdi-eye"></i></span>
                      <span> Details</span>
                    </a>
                  </button>
                </div>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>


  <div class="column is-3">
    <div class="card">
      <div class="card-header has-background-white-ter">
        <p class="card-header-title">
          Suggestions
        </p>
      </div>
      <div class="card-content">
        {% for suggestion in suggestions %}
          <div class="notification m-1">
            {{suggestion}}
          </div>
        {% endfor %}
      </div>
    </div>
    <div class="card mt-5">
      <header class="card-header has-background-white-ter">
        <p class="card-header-title">
          Help Desk
        </p>
      </header>
      <div class="card-content ">
        <div class="column ">
          <a class="button level is-info has-background-grey-dark mb-3 " href="#">
            <span> <i class="mdi mdi-phone"></i></span>
            Contact with driver </a>
          <a class="button level is-info has-background-grey-dark " href="#">
            <span> <i class="mdi mdi-message-text"></i></span>
            Contact with PTAI </a>
        </div>
      </div>
    </div>
  </div>

  {% endblock %}

server/templates/dashboard_index.html
{% extends 'dashboard/dashboard_base.html' %}

{% block content %}

<script>
  function sortTable() {
    // Declare variables
    var input, filter, table, tr, td, i, txtValue;
    input = document.getElementById("myInput");
    filter = input.value.toUpperCase();
    table = document.getElementById("vehicleDetailsTable");
    tr = table.getElementsByTagName("tr");

    // Loop through all table rows, and hide those who don't match the search query
    for (i = 0; i < tr.length; i++) {
      td = tr[i].getElementsByTagName("td")[1];
      if (td) {
        txtValue = td.textContent || td.innerText;
        if (txtValue.toUpperCase().indexOf(filter) > -1) {
          tr[i].style.display = "";
        } else {
          tr[i].style.display = "none";
        }
      }
    }
  }

  document.addEventListener('DOMContentLoaded', function () {
    const table = document.getElementById('vehicleDetailsTable');
    const tbody = table.querySelector('tbody');
    const sortDate = document.getElementById('sortDate');
    let ascending = true;

    function sortTable() {
      const rows = Array.from(tbody.querySelectorAll('tr'));

      rows.sort((a, b) => {
        const dateA = new Date(a.querySelector('td:nth-child(5)').textContent);
        const dateB = new Date(b.querySelector('td:nth-child(5)').textContent);

        if (ascending) {
          return dateA - dateB;
        } else {
          return dateB - dateA;
        }
      });

      tbody.innerHTML = '';
      for (const row of rows) {
        tbody.appendChild(row);
      }

      ascending = !ascending;
    }

    sortDate.addEventListener('click', sortTable);
  });

</script>

<div class="columns">
  <div class="column is-8">
    <div class="columns">
      <div class="column is-one-third">
        <div class="card tile is-child">
          <div class="card-content">
            <div class="level is-mobile">
              <div class="level-item">
                <div class="is-widget-label">
                  <h3 class="subtitle is-spaced">
                    Total
                  </h3>
                  <h1 class="title">
                    {{summary_information['total']}}
                  </h1>
                </div>
              </div>
              <div class="level-item has-widget-icon">
                <div class="is-widget-icon"><span class="icon has-text-primary is-large"><i
                      class="mdi mdi-train-car mdi-48px"></i></span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="column is-one-third">
        <div class="card tile is-child">
          <div class="card-content">
            <div class="level is-mobile">
              <div class="level-item">
                <div class="is-widget-label">
                  <h3 class="subtitle is-spaced">
                    Required
                  </h3>
                  <h1 class="title">
                    {{summary_information['required']}}
                  </h1>
                </div>
              </div>
              <div class="level-item has-widget-icon">
                <div class="is-widget-icon"><span class="icon has-text-warning is-large"><i
                      class="mdi mdi-information-box mdi-48px"></i></span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="column is-one-third">
        <div class="card tile is-child">
          <div class="card-content">
            <div class="level is-mobile">
              <div class="level-item">
                <div class="is-widget-label">
                  <h3 class="subtitle is-spaced">
                    Planned 
                  </h3>
                  <h1 class="title">
                    {{summary_information['planned']}}
                  </h1>
                </div>
              </div>
              <div class="level-item has-widget-icon">
                <div class="is-widget-icon"><span class="icon has-text-danger is-large"><i
                      class="mdi mdi-train-car-flatbed-car mdi-48px"></i></span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="card has-table">

      <header class="card-header has-background-white-ter">
        <p class="card-header-title">
          <span class="icon"><i class="mdi mdi-account-multiple"></i></span>
          Vehicles
        </p>
      </header>

      <div class="card-content">
        <div class="field is-grouped">
          <p class="control is-expanded">
            <input class="input" type="text" id="myInput" onkeyup="sortTable()"
              placeholder="Find a vehicle from licence plate...">
          </p>
          <p class="control">
            <a class="button is-primary" href="{{ url_for('PageRoutes.device_register') }}">
              Register New Vehicle
            </a>
          </p>
        </div>

        <table class="table is-striped is-hoverable is-fullwidth" id="vehicleDetailsTable">
          <thead>
            <tr>
              <th style="text-align: center;"><abbr title="Vehicle id">id</abbr></th>
              <th style="text-align: center;">Type</th>
              <th style="text-align: center;">Plate</th>
              <th style="text-align: center;">Route</th>
              <th style="text-align: center;">
                <a id="sortDate" class="sortable-header">
                  <span class="icon-text ">
                    <span>Predicted Date</span>
                    <span class="icon">
                      <i class="mdi mdi-sort-calendar-descending mdi mdi-24px"></i>
                    </span>
                  </span>
                </a>
              </th>
              <th style="text-align: center;"></th>
            </tr>
          </thead>
          <tbody>
            {% for vehicle in datatable %}
            <tr>
              <th>{{vehicle.id}}</th>
              <td>{{vehicle.class}}</td>
              <td>{{vehicle.plate}}</td>
              <td>{{vehicle.route}}</td>
              <td>{{vehicle.pmdate}}</td>
              <td class="is-actions-cell">
                <div class="buttons is-right">
                  <button class="button is-small is-light" type="button">
                    <a class="sortable-header" href="{{url_for('PageRoutes.view_details')}}">
                      <span class="icon"><i class="mdi mdi-eye"></i></span>
                      <span> Details</span>
                    </a>
                  </button>
                </div>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>


  <div class="column is-4">
    <div class="card">
      <div class="card-header has-background-white-ter">
        <p class="card-header-title">
          Suggestions
        </p>
      </div>
      <div class="card-content">
        {% for suggestion in suggestions %}
          <div class="notification m-1">
            {{suggestion}}
          </div>
        {% endfor %}
      </div>
    </div>
    <div class="card mt-5">
      <header class="card-header has-background-white-ter">
        <p class="card-header-title">
          Help Desk
        </p>
      </header>
      <div class="card-content ">
        <div class="column ">
          <a class="button level is-info has-background-grey-dark mb-3 " href="#">
            <span> <i class="mdi mdi-phone"></i></span>
            Contact with driver </a>
          <a class="button level is-info has-background-grey-dark " href="#">
            <span> <i class="mdi mdi-message-text"></i></span>
            Contact with PTAI </a>
        </div>
      </div>
    </div>
  </div>

  {% endblock %}

server/templates/home.html
{% extends 'profile_layout.html' %}
  
{% block title %}Home{% endblock %}
  
{% block content %}
<h1 class="h2">Dashboard</h1>
<p>Welcome back, {{ name_surname }}!</p>
{% endblock %}

server/templates/index.html
{% extends 'partials/base.html' %}

{% block content %}
<div class="columns is-centered is-mobile is-desktop">
    <div class="column is-one-third-desktop is-10-mobile mb-0">
        <figure class="image">
            <img src="./static/images/ptai_logo_gri.png"></img>
        </figure>
        <p class="subtitle is-size-6-desktop is-size-7-mobile has-text-right">Public Transportation Artificial
            Intelligence</p>
    </div>
</div>

<section class="section is-small mt-0">
    <div class="columns is-vcentered is-mobile">
        <div class="column is-one-third-desktop is-one-half-mobile">
            <h1 class="title has-text-centered has-text-justify is-size-5-mobile">PTAI is an AI tool for your company
            </h1>
            <p class="subtitle is-size-6-mobile">Artificial Intelligence makes decisions more punctually!</p>
        </div>
        <div class="column is-hidden-mobile">
            <img src="./static/images/index.png">
        </div>
        <div class="column is-one-third-desktop is-one-half-mobile">
            <h1 class="title has-text-centered has-text-justify is-size-5-mobile">PTAI manages companies' operations
            </h1>
            <p class="subtitle is-size-6-mobile">In order to not waste your time with glitches, we are warning you
                before happen!</p>
        </div>
    </div>
</section>

<figure class="image is-hidden-desktop is-64x64-mobile">
    <img src="./static/images/index.png"></img>
</figure>

<section class="section is-small">
    <div class="columns is-centered has-text-centered has-text-justify is-mobile ">
        <div class="column ">
            <h1 class="title is-size-5-mobile">PTAI provides after sales support </h1>
            <p class="subtitle is-size-6-mobile ">Our team always work for you. You can reach us whenever you want!</p>
        </div>

    </div>
</section>


<section class="section is-large">
    <div class="columns">
        <div class="column is-one-half">
            <figure class="image is-2by1">
                <img width="500" height="250" src="./static/images/in_graph.png"></img>
            </figure>
        </div>
        <div class="column is-one-half">
            <h1 class="title is-size-4-mobile">What is PTAI ?</h1>
            <p class="subtitle is-size-6-mobile">PTAI is an AI-based predictive maintenance optimization tool for
                company's
                operations.
                With PTAI, you can minimize downtime, reduce maintenance costs, and maximize the efficiency of your
                operations.<br>
                PTAI utilizes machine learning algorithms, IoT sensors, and predictive analytics to monitor the
                health of your vehicles and
                predict when maintenance is needed before a breakdown occurs.</p>
            <div class="buttons is-centered">
                <a class="button is-dark" href="{{ url_for('PageRoutes.project_details')}}">Learn more</a>
            </div>

        </div>
    </div>
</section>



<div class="section has-background-white-ter is-mobile">
    <div class="title has-text-centered is-size-4-mobile">
        Sustainable Development Goals
    </div>
    <div class="columns is-mobile is-centered is-desktop ">
        <div class="column is-one-quarter-desktop is-one-third-mobile">
            <figure class="image is-1by1">
                <img src="./static/images/SDG/SDG-8.svg"></img>
            </figure>
        </div>
        <div class="column is-one-quarter-desktop is-one-third-mobile">
            <figure class="image is-1by1">
                <img src="./static/images/SDG/SDG-9.svg"></img>
            </figure>
        </div>
        <div class="column is-one-quarter-desktop is-one-third-mobile">
            <figure class="image is-1by1">
                <img src="./static/images/SDG/SDG-11.svg"></img>
            </figure>
        </div>
    </div>
</div>

{% endblock %}

server/templates/login.html
{% extends 'partials/base.html' %}

{% block content %}
<div class="container">

  <form action="/login" method="post" class="box custom-box is-centered">
    <div class="field is-vcentered">
      <label class="label">Email</label>
      <div class="control has-icons-left">
        <span class="icon is-small is-left">
          <i class="mdi mdi-email"></i>
        </span>
        <input class="input" type="email" name="email" placeholder="e.g. alex@example.com">
      </div>
    </div>

    <div class="field">
      <label class="label">Password</label>
      <div class="control has-icons-left">
        <span class="icon is-small is-left">
          <i class="mdi mdi-lock"></i>
        </span>
        <input class="input" type="password" name="password" placeholder="********">
      </div>
    </div>

    <div class="buttons">
      <input class="button is-primary" type="submit" value="Login">
      <p class="content"> Don't you have an account? <a href="{{ url_for('PageRoutes.signup')}}">Signup</a></p>
    </div>
  </form>

</div>

{%endblock%}